version: '3'
services:
  db:
    build: .
    ports:
     - "5432:5432"
  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test